### ISSUE TITLE
Silkspawners Crashes When Enabling on Server Startup

### ISSUE THREAD

**Issue by GrainsofSalt** [timbru31/SilkSpawners#141]
## What steps will reproduce the problem?
Enabling the plugin on my server
## Expected output
The plugin will load successfully
## What do you see instead?
Plugin, crashes, errors, and disables
## Log file of the issue/error
[17:33:58 WARN]: java.lang.ClassNotFoundException: de.dustplanet.silkspawners.compat.null.NMSHandler
[17:33:58 WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[17:33:58 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
[17:33:58 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[17:33:58 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:33:58 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:33:58 WARN]: at java.lang.Class.forName0(Native Method)
[17:33:58 WARN]: at java.lang.Class.forName(Class.java:264)
[17:33:58 WARN]: at de.dustplanet.util.SilkUtil.setupNMSProvider(SilkUtil.java:150)
[17:33:58 WARN]: at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:122)
[17:33:58 WARN]: at de.dustplanet.util.SilkUtil.hookIntoSilkSpanwers(SilkUtil.java:139)
[17:33:58 WARN]: at com.pablo67340.shop.main.Main.onEnable(Main.java:130)
[17:33:58 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:33:58 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[17:33:58 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:33:58 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[17:33:58 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[17:33:58 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[17:33:58 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[17:33:58 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[17:33:58 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293)
[17:33:58 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[17:33:58 WARN]: at java.lang.Thread.run(Thread.java:748)
[17:33:58 ERROR]: [SilkSpawners] Could not find support for this CraftBukkit version.
## /version output?
[21:07:45 INFO]: This server is running Paper version git-Paper-1499 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

## SilkSpawners version
Version v5.0.2

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by GrainsofSalt** [comment]
Anyone?

**Comment by timbru31** [comment]
Have you tried a newer Paper version? Your version is quite old. Seems that https://destroystokyo.com/ci/job/Paper/1533/ is the latest (1533)

**Comment by GrainsofSalt** [comment]
I just tried using that version. Same exact error.

**Comment by timbru31** [comment]
Thanks, I'll spin up a PaperMC server and debug what's wrong.

**Comment by GrainsofSalt** [comment]
Thank you so much!

**Comment by GrainsofSalt** [comment]
Hey man,

Any luck yet?

**Comment by Zyrexus** [comment]
I'm also getting the same problem but I'm using a diff version that's based off TacoSpigot (FluxSpigot, fixes cannons) that's based off paper spigot:

`This server is running CraftBukkit version FluxSpigot-204a0878 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
Unknown version, custom build?`

same error,
`[17:38:00] [Server thread/INFO]: [SilkSpawners] WorldGuard support is disabled due to config setting
[17:38:00] [Server thread/WARN]: java.lang.ClassNotFoundException: de.dustplanet.silkspawners.compat.null.NMSHandler
[17:38:00] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[17:38:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[17:38:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[17:38:00] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:38:00] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:38:00] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[17:38:00] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[17:38:00] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.setupNMSProvider(SilkUtil.java:150)
[17:38:00] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:122)
[17:38:00] [Server thread/WARN]: 	at net.brcdev.shopgui.provider.spawner.SpawnerSilkSpawnersProvider.hook(SpawnerSilkSpawnersProvider.java:16)
[17:38:00] [Server thread/WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.setupSpawners(ShopGuiPlugin.java:325)
[17:38:00] [Server thread/WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.onEnable(ShopGuiPlugin.java:143)
[17:38:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[17:38:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[17:38:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[17:38:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:313)
[17:38:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:272)
[17:38:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[17:38:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[17:38:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[17:38:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[17:38:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[17:38:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[17:38:00] [Server thread/ERROR]: [SilkSpawners] Could not find support for this CraftBukkit version.
[17:38:00] [Server thread/INFO]: [SilkSpawners] Check for updates at https://dev.bukkit.org/projects/silkspawners/
[17:38:00] [Server thread/INFO]: [SilkSpawners] Disabling SilkSpawners now!`

**Comment by GrainsofSalt** [comment]
Any ideas on what could be calling it? It looks like there is a dependency
missing or something?

**Comment by timbru31** [comment]
I'm unable to reproduce the issue.

Can you please provide some more information?

- your OS
- your Java version (OpenJRE or OracleJRE?)

Have you tried just starting the server with only SilkSpawners installed?

**Comment by Zyrexus** [comment]
My java version is:
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
and OS: Ubuntu 16.04, I'm not sure about GrainofSalts version.

**Comment by timbru31** [comment]
Wait, looking closer:

`[17:33:58 WARN]: at com.pablo67340.shop.main.Main.onEnable(Main.java:130)`
 The error is not caused by regular startup.
@GrainsofSalt What version of GUIShop are you using?

---
and respectively
`[17:38:00] [Server thread/WARN]: at net.brcdev.shopgui.ShopGuiPlugin.setupSpawners(ShopGuiPlugin.java:325)`

@Zyrexus what version of ShopGUI+ are you using?

**Comment by Zyrexus** [comment]
The latest version

**Comment by GrainsofSalt** [comment]
> I updated my GUISHOP version and it worked


Thanks Guys!

>

**Comment by timbru31** [comment]
@Zyrexus Since ShopGUI+ is closed source I can't assist you any further :(
You have to seek support in the SpigotMC forums thread.
