### ISSUE TITLE
Report about 1.13 dev build

### ISSUE THREAD

**Issue by FabioZumbi12** [timbru31/SilkSpawners#144]
_I have ignored the issue template because its just a report about the dev build for 1.13_

```
[00:40:17 INFO]: [SilkSpawners] Enabling SilkSpawners v6.0.0-SNAPSHOT-b479
[00:40:17 INFO]: [SilkSpawners] WorldGuard was not found and support is disabled
[00:40:17 INFO]: [SilkSpawners] Loading support for v1_13_R1
[00:40:17 ERROR]: Error occurred while enabling SilkSpawners v6.0.0-SNAPSHOT-b479 (Is it up to date?)
java.lang.NoSuchFieldError: ID_MAPPING
        at de.dustplanet.silkspawners.compat.v1_13_R1.NMSHandler.rawEntityMap(NMSHandler.java:117) ~[?:?]
        at de.dustplanet.util.SilkUtil.scanEntityMap(SilkUtil.java:758) ~[?:?]
        at de.dustplanet.util.SilkUtil.load(SilkUtil.java:173) ~[?:?]
        at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:118) ~[?:?]
        at de.dustplanet.silkspawners.SilkSpawners.onEnable(SilkSpawners.java:90) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.jar:git-Paper-134]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.jar:git-Paper-134]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.jar:git-Paper-134]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433) ~[patched_1.13.jar:git-Paper-134]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[patched_1.13.jar:git-Paper-134]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:589) ~[patched_1.13.jar:git-Paper-134]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:551) ~[patched_1.13.jar:git-Paper-134]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:428) ~[patched_1.13.jar:git-Paper-134]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.jar:git-Paper-134]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-134]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[00:40:17 INFO]: [SilkSpawners] Disabling SilkSpawners v6.0.0-SNAPSHOT-b479
```
Using with latest dev build of paperclip: https://destroystokyo.com/ci/job/Paper-1.13/134/

**Comment by timbru31** [comment]
Interesting, thanks for the report!

**Comment by nekohuntr** [comment]
We're having the same issue on Paper 1.13 build 158 and SilkSpawners b481:
`[10:31:23] [Server thread/INFO]: [SilkSpawners] Enabling SilkSpawners v6.0.0-SNAPSHOT-b481
[10:31:23] [Server thread/INFO]: [SilkSpawners] WorldGuard was not found and support is disabled
[10:31:23] [Server thread/INFO]: [SilkSpawners] Loading support for v1_13_R1
[10:31:23] [Server thread/ERROR]: Error occurred while enabling SilkSpawners v6.0.0-SNAPSHOT-b481 (Is it up to date?)
java.lang.NoSuchFieldError: ID_MAPPING
	at de.dustplanet.silkspawners.compat.v1_13_R1.NMSHandler.rawEntityMap(NMSHandler.java:117) ~[?:?]
	at de.dustplanet.util.SilkUtil.scanEntityMap(SilkUtil.java:724) ~[?:?]
	at de.dustplanet.util.SilkUtil.load(SilkUtil.java:173) ~[?:?]
	at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:118) ~[?:?]
	at de.dustplanet.silkspawners.SilkSpawners.onEnable(SilkSpawners.java:90) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.jar:git-Paper-158]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.jar:git-Paper-158]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.jar:git-Paper-158]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.jar:git-Paper-158]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.jar:git-Paper-158]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:724) ~[patched_1.13.jar:git-Paper-158]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1752) ~[patched_1.13.jar:git-Paper-158]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1556) ~[patched_1.13.jar:git-Paper-158]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.jar:git-Paper-158]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.jar:git-Paper-158]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.jar:git-Paper-158]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_77]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[patched_1.13.jar:git-Paper-158]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:987) ~[patched_1.13.jar:git-Paper-158]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-158]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:915) ~[patched_1.13.jar:git-Paper-158]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:813) ~[patched_1.13.jar:git-Paper-158]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[10:31:23] [Server thread/INFO]: [SilkSpawners] Disabling SilkSpawners v6.0.0-SNAPSHOT-b481`
