### ISSUE TITLE
Silkspawners not working

### ISSUE THREAD

**Issue by sandor111** [timbru31/SilkSpawners#146]
[13:32:52] [Server thread/INFO]: [SilkSpawners] WorldGuard was found and support is enabled
[13:32:52] [Server thread/WARN]: java.lang.ClassNotFoundException: de.dustplanet.silkspawners.compat.null.NMSHandler
[13:32:52] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[13:32:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[13:32:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[13:32:52] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:32:52] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:32:52] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[13:32:52] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[13:32:52] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.setupNMSProvider(SilkUtil.java:150)
[13:32:52] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:122)
[13:32:52] [Server thread/WARN]: 	at net.brcdev.shopgui.provider.spawner.SpawnerSilkSpawnersProvider.hook(SpawnerSilkSpawnersProvider.java:16)
[13:32:52] [Server thread/WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.setupSpawners(ShopGuiPlugin.java:328)
[13:32:52] [Server thread/WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.onEnable(ShopGuiPlugin.java:145)
[13:32:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[13:32:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[13:32:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[13:32:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[13:32:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[13:32:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[13:32:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[13:32:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[13:32:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[13:32:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[13:32:52] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by timbru31** [comment]
`[13:32:52] [Server thread/WARN]: at net.brcdev.shopgui.ShopGuiPlugin.onEnable(ShopGuiPlugin.java:145)`

Issue is caused by ShopGUI+, since it's closed source please seek support in the SpigotMC thread.
