### ISSUE TITLE
Breaking a spawner does not drop spawner.

### ISSUE THREAD

**Issue by teozfrank** [timbru31/SilkSpawners#147]
## What steps will reproduce the problem?
Using worldguard 7.0.0 snapshot ;380938cff7c- breaking a spawner with a silk touch pick creates a server error and the block breaks without dropping.

## Expected output
Break the spawner with a silk touch pick and the spawner should drop

## What do you see instead?
Spawner breaks, nothing drops

## Log file of the issue/error
> [00:17:46 ERROR]: Could not pass event BlockBreakEvent to SilkSpawners v6.0.0-SNAPSHOT-b479
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-417cfb3-96778ca]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-417cfb3-96778ca]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-417cfb3-96778ca]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-417cfb3-96778ca]
at net.minecraft.server.v1_13_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[server.jar:git-Spigot-417cfb3-96778ca]
at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) ~[server.jar:git-Spigot-417cfb3-96778ca]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1166) ~[server.jar:git-Spigot-417cfb3-96778ca]
at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[server.jar:git-Spigot-417cfb3-96778ca]
at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[server.jar:git-Spigot-417cfb3-96778ca]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-417cfb3-96778ca]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [server.jar:git-Spigot-417cfb3-96778ca]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [server.jar:git-Spigot-417cfb3-96778ca]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [server.jar:git-Spigot-417cfb3-96778ca]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [server.jar:git-Spigot-417cfb3-96778ca]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [server.jar:git-Spigot-417cfb3-96778ca]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.canBuild(Lorg/bukkit/entity/Player;Lorg/bukkit/Location;)Z
at de.dustplanet.util.SilkUtil.canBuildHere(SilkUtil.java:966) ~[?:?]
at de.dustplanet.silkspawners.listeners.SilkSpawnersBlockListener.onBlockBreak(SilkSpawnersBlockListener.java:62) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-417cfb3-96778ca]
## /version output?
git-spigot-417cfb3-96778ca (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

## SilkSpawners version

6.0.0-SNAPSHOT-b479

## Please provide any additional information below.

I can confirm without using WorldGuard the spawner drops as intended.

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
I guess you are using WoldGuard v7?

**Comment by timbru31** [comment]
WorldGuard v7 support is disabled for the meantime since the underlying APIs have been removed.
