### ISSUE TITLE
Everytime I change craftablespawners to "true" the plugin breaks

### ISSUE THREAD

**Issue by NoLimitMatthew** [timbru31/SilkSpawners#163]
## What steps will reproduce the problem?
Going into the config and changing the craftable spawner to true.
## Expected output
To be able to craft spawners
## What do you see instead?
Everytime I type "/ss help" it replies with the message I type
## Log file of the issue/error

```
[00:56:03] [Server thread/INFO]: [SilkSpawners] Enabling SilkSpawners v5.0.2
[00:56:04] [Server thread/INFO]: [SilkSpawners] WorldGuard was not found and support is disabled
[00:56:04] [Server thread/INFO]: [SilkSpawners] Loading support for v1_11_R1
[00:56:04] [Server thread/ERROR]: Error occurred while enabling SilkSpawners v5.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
	at de.dustplanet.silkspawners.SilkSpawners.loadRecipes(SilkSpawners.java:279) ~[?:?]
	at de.dustplanet.silkspawners.SilkSpawners.loadConfig(SilkSpawners.java:260) ~[?:?]
	at de.dustplanet.silkspawners.SilkSpawners.onEnable(SilkSpawners.java:94) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:360) [craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:322) [craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.ClassNotFoundException: org.bukkit.NamespacedKey
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.11.jar:git-Bukkit-0a81101]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	... 14 more
```

## /version output?

This server is running CraftBukkit version git-Bukkit-0a81101 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

## SilkSpawners version
SilkSpawners v5.0.2 --1.5 up to 1.12.2--

## Please provide any additional information below.
I tried adding the permission to the permissions list but that didn't fix the problem.
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Strange. This should have been fixed with 10042ea543847311e972773518085ac2372d2256 -I'll debug 1.11
