### ISSUE TITLE
SilkUtil.hookIntoSilkSpanwers();

### ISSUE THREAD

**Issue by Zsmith21** [timbru31/SilkSpawners#166]
## What steps will reproduce the problem?
 silkUtil = SilkUtil.hookIntoSilkSpanwers();
## Expected output
SilkUtil != null
## What do you see instead?
java.lang.NullPointerException
        at de.dustplanet.util.SilkUtil.getWorldGuard(SilkUtil.java:873) ~[?:?]
        at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:118) ~[?:?]
        at de.dustplanet.util.SilkUtil.hookIntoSilkSpanwers(SilkUtil.java:130) ~[?:?]
        at me.therealdan.tribes.mechanics.MobSpawners.<init>(MobSpawners.java:18) ~[?:?]
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [ ] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Please provide more code snippets and valid version information, otherwise I'm unable to help.

**Comment by timbru31** [comment]
Closing due to lack of feedback.
