### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by TheCamoWaffle** [timbru31/SilkSpawners#173]
## Expected output
It's a startup error.
## What do you see instead?
Error.
## Log file of the issue/error
[SilkSpawners] WorldGuard was found and support is enabled
[12:10:45 WARN]: java.lang.ClassNotFoundException: de.dustplanet.silkspawners.compat.null.NMSHandler
[12:10:45 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[12:10:45 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[12:10:45 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[12:10:45 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:10:45 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:10:45 WARN]:        at java.lang.Class.forName0(Native Method)
[12:10:45 WARN]:        at java.lang.Class.forName(Unknown Source)
[12:10:45 WARN]:        at de.dustplanet.util.SilkUtil.setupNMSProvider(SilkUtil.java:150)
[12:10:45 WARN]:        at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:122)
[12:10:45 WARN]:        at net.brcdev.shopgui.provider.spawner.SpawnerSilkSpawnersProvider.hook(SpawnerSilkSpawnersProvider.java:16)
[12:10:45 WARN]:        at net.brcdev.shopgui.ShopGuiPlugin.setupSpawners(ShopGuiPlugin.java:325)
[12:10:45 WARN]:        at net.brcdev.shopgui.ShopGuiPlugin.onEnable(ShopGuiPlugin.java:143)
[12:10:45 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[12:10:45 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[12:10:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[12:10:45 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:360)
[12:10:45 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:319)
[12:10:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[12:10:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[12:10:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[12:10:45 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[12:10:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[12:10:45 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:10:45 ERROR]: [SilkSpawners] Could not find support for this CraftBukkit version.
[12:10:45 INFO]: [SilkSpawners] Check for updates at https://dev.bukkit.org/projects/silkspawners/
[12:10:45 INFO]: [SilkSpawners] Disabling SilkSpawners now!
[12:10:45 INFO]: [ShopGUIPlus] SilkSpawners support enabled.

## /version output?
[12:14:38 INFO]: This server is running CraftBukkit version git-TacoSpigot-fd3209f3 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[12:14:38 INFO]: Checking version, please wait...
[12:14:38 INFO]: Check https://www.mc-market.org/resources/5376/ for updates

## SilkSpawners version
v5.0.2

I haven't touched the config at all.

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
The issue is thrown by ShopGUI+, since it's closed source I can't assist any further, but I believe more recent versions are no longer affected of this bug.
