### ISSUE TITLE
java.lang.ClassNotFoundException: de.dustplanet.silkspawners.compat.null.NMSHandler

### ISSUE THREAD

**Issue by Ambu80** [timbru31/SilkSpawners#180]
## Log file of the issue/error
http://prntscr.com/lmwmjl
## /version output?
SPIGOT 1.8.8

http://prntscr.com/lmwnd4

**Comment by Ambu80** [comment]
[12:44:17] [Server thread/WARN]: java.lang.ClassNotFoundException: de.dustplanet.silkspawners.compat.null.NMSHandler
[12:44:17] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[12:44:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[12:44:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[12:44:17] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:44:17] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:44:17] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[12:44:17] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[12:44:17] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.setupNMSProvider(SilkUtil.java:150)
[12:44:17] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:122)
[12:44:17] [Server thread/WARN]: 	at net.brcdev.shopgui.provider.spawner.SpawnerSilkSpawnersProvider.hook(SpawnerSilkSpawnersProvider.java:16)
[12:44:17] [Server thread/WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.setupSpawners(ShopGuiPlugin.java:325)
[12:44:17] [Server thread/WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.onEnable(ShopGuiPlugin.java:143)
[12:44:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[12:44:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[12:44:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[12:44:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[12:44:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[12:44:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[12:44:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[12:44:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[12:44:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[12:44:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[12:44:17] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by timbru31** [comment]
Please add the required information from the issue template, I can't help you otherwise.

**Comment by timbru31** [comment]
Closing due to lack of feedback.
