### ISSUE TITLE
Building from GitHub download

### ISSUE THREAD

**Issue by MXR156** [timbru31/SilkSpawners#189]
I have cloned the whole repo in Eclipse to try and build the Java file for SilkSpawners but cant seem to build it, everything seems to fail. Which section is needed to download to allow me to import this into Oxygen and build as a jar file for use on my server?

My server is 1.13 therefor only supported through the builds on GitHub. I dont necessarily have to use Oxygen, but how would I build the Jar file?

**Comment by MXR156** [comment]
This is the error I receive after compiling. I have moved the yml files in resources into the root of the plugin as it was saying invalid plugin.yml file beforehand

`[20:26:01 ERROR]: Could not load 'plugins\SilkSpawners.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.Error: Unresolved compilation problems:
        The import org.bstats cannot be resolved
        The import net.gravitydevelopment cannot be resolved
        Updater cannot be resolved to a type
        Updater cannot be resolved to a type
        Updater cannot be resolved to a type
        Updater cannot be resolved to a variable
        Updater cannot be resolved to a type
        Metrics cannot be resolved to a type
        The method setBarAPI(boolean) is undefined for the type SilkUtil
        The method getDisplayNameToMobID() is undefined for the type SilkUtil
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type
        The method getMobIDToDisplayName() is undefined for the type SilkUtil
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type

        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:136) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:323) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.Error: Unresolved compilation problems:
        The import org.bstats cannot be resolved
        The import net.gravitydevelopment cannot be resolved
        Updater cannot be resolved to a type
        Updater cannot be resolved to a type
        Updater cannot be resolved to a type
        Updater cannot be resolved to a variable
        Updater cannot be resolved to a type
        Metrics cannot be resolved to a type
        The method setBarAPI(boolean) is undefined for the type SilkUtil
        The method getDisplayNameToMobID() is undefined for the type SilkUtil
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type
        The method getMobIDToDisplayName() is undefined for the type SilkUtil
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type
        NMSProvider cannot be resolved to a type

        at de.dustplanet.silkspawners.SilkSpawners.<init>(SilkSpawners.java:12) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_191]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:70) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:132) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        ... 6 more`

**Comment by timbru31** [comment]
You need to use Maven to package the complete SilkSpawners.

Due to the DMCA on CraftBukkit, I'm unable to distribute the required craftbukkit.jar files publicly. You need to get them yourself. Google might help ;)

**Comment by MXR156** [comment]
Ahh that's a pain, I will take a look. I have never used Maven before and dont seem to have had any luck with anything before haha. I will see what I can do. I have the required files already so that't not the issue. The issue is the file structure as the pull request takes them all down in a rather strange structure compared to my current Java projects but I'll see what I can do.

**Comment by timbru31** [comment]
I'm closing this issue. If you have specific questions regarding the build process, feel free to reply here.
