### ISSUE TITLE
Version 503 basically un-usable

### ISSUE THREAD

**Issue by pablo67340** [timbru31/SilkSpawners#197]
## What steps will reproduce the problem?
Simply install SilkSpawners #503, hook into SilkUtil and set the spawner using the entity ID. When you place the spawner, it successfully says "Placed {mob} Spawner". For a split second you'll see the correct mob inside the spawner, then all of the sudden it changes to a pig. When you break the spawner, out comes a stack trace.

## Expected output
The spawner should place the correct mob once, and break without errors.

## What do you see instead?
Errors & the details I already mentioned above.

## Log file of the issue/error
`[14:41:15] [Server thread/ERROR]: Could not pass event BlockBreakEvent to SilkSpawners v6.0.0-SNAPSHOT-b503
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[minecraft.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:215) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:640) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_202]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [minecraft.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[?:1.8.0_202]
	at de.dustplanet.util.SilkUtil.getCreatureName(SilkUtil.java:562) ~[?:?]
	at de.dustplanet.silkspawners.listeners.SilkSpawnersBlockListener.onBlockBreak(SilkSpawnersBlockListener.java:76) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[minecraft.jar:git-PaperSpigot-"4c7641d"]
	... 18 more`
## /version output?
CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) Implementing API version 1.8.8-R0.1-SNAPSHOT

## SilkSpawners version

Development Build #503

## Please provide any additional information below.

[https://youtu.be/DQ5eI2thgeA](https://youtu.be/DQ5eI2thgeA)

* Slow the video down to half speed to clearly see the initial mob being correctly selected, then changing to a pig. 

At this point, the plugin is basically useless when used with GUIShop or any other plugin using SilkUtil. 

Configurations are default and untouched. 

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
It's a development build, that means: bugs, instability and not working builds.  
You are using MC 1.8.8, please stick to SilkSpawners v5.0.2 from BukkitDev

**Comment by pablo67340** [comment]
See, thing is, I would stick to that build, if the API wasn't completely different for setting an item stack mob type. I really shouldn't need to be adding support per each version of silk when you have compatibility fixes in the latest version of silk for 1.13 and below.

**Comment by timbru31** [comment]
Sorry, I've misread your issue that you are using the API :)  
Your reported issue is basically #152 - same stack trace

**Comment by pablo67340** [comment]
Ah yes, Hopefully my recording and stack can provide you some assistance. Later this week ill look into forking and fixing myself if you're short on time. I have a ton of people complaining GUIShop spawners aren't working when in-turn its silk :c
