### ISSUE TITLE
Exception while loading the file: while parsing a block collection

### ISSUE THREAD

**Issue by spommerening** [timbru31/SilkSpawners#330]
SilkSpawners version 7.1.0

Minecraft Server is PaperMC build #61:
`This server is running Paper version git-Paper-61 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 45ec379)`

While loading the server / plugin I get the following warning messages: 

```
[...]
[17:23:58] [Server thread/INFO]: [SilkSpawners] Enabling SilkSpawners v7.1.0
[17:23:58] [Server thread/INFO]: Exception while loading the file: while parsing a block collection
[17:23:58] [Server thread/INFO]:  in 'string', line 805, column 5:
[17:23:58] [Server thread/INFO]:         - glowsq
[17:23:58] [Server thread/INFO]:         ^
[17:23:58] [Server thread/INFO]: expected <block end>, but found '?'
[17:23:58] [Server thread/INFO]:  in 'string', line 811, column 5:
[17:23:58] [Server thread/INFO]:         enable: true
[17:23:58] [Server thread/INFO]:         ^
[17:23:58] [Server thread/INFO]:
[17:23:58] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while parsing a block collection
[17:23:58] [Server thread/WARN]:  in 'string', line 805, column 5:
[17:23:58] [Server thread/WARN]:         - glowsq
[17:23:58] [Server thread/WARN]:         ^
[17:23:58] [Server thread/WARN]: expected <block end>, but found '?'
[17:23:58] [Server thread/WARN]:  in 'string', line 811, column 5:
[17:23:58] [Server thread/WARN]:         enable: true
[17:23:58] [Server thread/WARN]:         ^
[17:23:58] [Server thread/WARN]:
[17:23:58] [Server thread/WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[17:23:58] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[17:23:58] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[17:23:58] [Server thread/WARN]:        at de.dustplanet.util.CommentedConfiguration.load(CommentedConfiguration.java:71)
[17:23:58] [Server thread/WARN]:        at de.dustplanet.silkspawners.configs.AbstractConfiguration.loadConfig(AbstractConfiguration.java:22)
[17:23:58] [Server thread/WARN]:        at de.dustplanet.silkspawners.configs.Mobs.loadConfig(Mobs.java:15)
[17:23:58] [Server thread/WARN]:        at de.dustplanet.silkspawners.SilkSpawners.initializeConfigs(SilkSpawners.java:245)
[17:23:58] [Server thread/WARN]:        at de.dustplanet.silkspawners.SilkSpawners.onEnable(SilkSpawners.java:74)
[17:23:58] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:23:58] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:23:58] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[17:23:58] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[17:23:58] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[17:23:58] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[17:23:58] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
[17:23:58] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[17:23:58] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[17:23:58] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[17:23:58] [Server thread/WARN]: Caused by: while parsing a block collection
[17:23:58] [Server thread/WARN]:  in 'string', line 805, column 5:
[17:23:58] [Server thread/WARN]:         - glowsq
[17:23:58] [Server thread/WARN]:         ^
[17:23:58] [Server thread/WARN]: expected <block end>, but found '?'
[17:23:58] [Server thread/WARN]:  in 'string', line 811, column 5:
[17:23:58] [Server thread/WARN]:         enable: true
[17:23:58] [Server thread/WARN]:         ^
[17:23:58] [Server thread/WARN]:
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:555)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:251)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:193)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[17:23:58] [Server thread/WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[17:23:58] [Server thread/WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[17:23:58] [Server thread/WARN]:        ... 17 more
[17:23:58] [Server thread/INFO]: [SilkSpawners] WorldGuard was found and support is enabled
[17:23:58] [Server thread/INFO]: [SilkSpawners] Loading support for v1_17_R1
[17:23:58] [Server thread/INFO]: [SilkSpawners] Entity marker is not in the config. Adding...
[17:23:58] [Server thread/INFO]: [SilkSpawners] AutoUpdater is enabled and now running.
[17:23:58] [Server thread/INFO]: [SilkSpawners] BarAPI is disabled due to config setting.
[...]
[17:24:00] [Server thread/INFO]: Running delayed init tasks
[17:24:00] [Server thread/INFO]: [SilkSpawners] Result from AutoUpdater is: NO_UPDATE
[...]
```

**Comment by timbru31** [comment]
Please delete the contents of your mobs.yml (not the file) and restart. Already fixed in the master branch or the latest dev-builds.
