### ISSUE TITLE
Plugin broken in 1.18

### ISSUE THREAD

**Issue by Sethenor** [timbru31/SilkSpawners#342]
## What steps will reproduce the problem?
Start 1.18 server with plugin installed

## Expected output
Working plugin

## What do you see instead?
```
[10:20:43 INFO]: [SilkSpawners] Enabling SilkSpawners v7.1.0
[10:20:43 INFO]: [SilkSpawners] This version of the plugin is NOT compatible with your Minecraft version!
[10:20:43 INFO]: [SilkSpawners] Please check your versions to make sure they match!
[10:20:43 INFO]: [SilkSpawners] Disabling now!
[10:20:43 INFO]: [SilkSpawners] Compatible versions are: [v1_8_R1, v1_8_R3, v1_9_R2, v1_10_R1, v1_11_R1, v1_12_R1, v1_13_R2, v1_14_R1, v1_15_R1, v1_16_R1, v1_16_R2, v1_16_R3, v1_17_R1]
[10:20:43 INFO]: [SilkSpawners] Your version is: v1_18_R1
[10:20:43 INFO]: [SilkSpawners] You can disable this check by setting testMCVersion to false in the config!
```

## /version output?
```
[10:32:27 INFO]: Checking version, please wait...
[10:32:27 INFO]: This server is running Paper version git-Paper-39 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 62fd374)
You are running the latest version
Previous version: git-Paper-36 (MC: 1.18)
```

## SilkSpawners version
`org.bukkit.command.CommandException: Cannot execute command 'silkspawners' in plugin **SilkSpawners v7.1.0** - plugin is disabled.`

## Please provide any additional information below.
If I disable the version check and load the plugin, this shows:

```
[10:40:25 ERROR]: [SilkSpawners] Could not find support for this CraftBukkit version.
[10:40:25 INFO]: [SilkSpawners] Check for updates at https://dev.bukkit.org/projects/silkspawners/
[10:40:25 INFO]: [SilkSpawners] Disabling SilkSpawners now!
[10:40:25 INFO]: [SilkSpawners] AutoUpdater is enabled and now running.
[10:40:25 ERROR]: Error occurred while enabling SilkSpawners v7.1.0 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register de.dustplanet.silkspawners.listeners.SilkSpawnersBlockListener@4449ecea while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:657) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at de.dustplanet.silkspawners.SilkSpawners.onEnable(SilkSpawners.java:134) ~[SilkSpawners.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-39]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-39]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:40:25 WARN]: Exception in thread "Thread-14" org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[10:40:25 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552)
[10:40:25 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227)
[10:40:25 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212)
[10:40:25 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176)
[10:40:25 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:145)
[10:40:25 WARN]:        at org.bukkit.scheduler.BukkitRunnable.runTask(BukkitRunnable.java:45)
[10:40:25 WARN]:        at SilkSpawners.jar//de.dustplanet.util.Updater.runUpdater(Updater.java:865)
[10:40:25 WARN]:        at SilkSpawners.jar//de.dustplanet.util.Updater.lambda$new$0(Updater.java:320)
[10:40:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Yes, that is expected. 1.18 is not supported. Please be patient.

**Comment by Sethenor** [comment]
Yep, was aware of that. Just letting you know above information in case it's any use to you :)

**Comment by timbru31** [comment]
Added via https://github.com/timbru31/SilkSpawners/commit/7a17213c5416a1cfa32f2b2f0579bd2afbd7113f
