### ISSUE TITLE
broken spawner comes without the mob

### ISSUE THREAD

**Issue by pump61** [timbru31/SilkSpawners#469]
Broke a spawners using silktouch

the spawner comes without the mob

[14:06:09 ERROR]: Could not pass event BlockPlaceEvent to SilkSpawners v7.5.1-SNAPSHOT-b323
java.lang.NoSuchMethodError: 'net.minecraft.util.RandomSource net.minecraft.world.level.GeneratorAccess.y_()'
        at de.dustplanet.silkspawners.compat.v1_20_R2.NMSHandler.setMobNameOfSpawner(NMSHandler.java:205) ~[SilkSpawners.jar:?]
        at de.dustplanet.util.SilkUtil.setSpawnerEntityID(SilkUtil.java:524) ~[SilkSpawners.jar:?]
        at de.dustplanet.silkspawners.listeners.SilkSpawnersBlockListener.onBlockPlace(SilkSpawnersBlockListener.java:282) ~[SilkSpawners.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor815.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-240]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-240]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-240]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:448) ~[paper-1.20.2.jar:git-Paper-240]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:423) ~[paper-1.20.2.jar:git-Paper-240]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:600) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1907) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-240]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-240]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-240]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-240]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Silkspawners 7.5.1-SNAPSHOT-b323

This server is running Paper version git-Paper-240 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: e57af7d)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-234 (MC: 1.20.2)

![image](https://github.com/timbru31/SilkSpawners/assets/61327951/e1eeaf73-d041-4e18-9e0a-b2af4dafb041)
![image](https://github.com/timbru31/SilkSpawners/assets/61327951/9b3000d7-a7bd-4207-891f-a9f00cc7c93d)
![image](https://github.com/timbru31/SilkSpawners/assets/61327951/c57785cf-d37f-4b97-86e4-e9898e39c89a)
![image](https://github.com/timbru31/SilkSpawners/assets/61327951/7e806f46-1893-4f08-9a70-fadb0f9c0091)

**Comment by timbru31** [comment]
👋 Hi there!

We're kicking off the new year with some housekeeping in our repository to keep things organized and up-to-date. As part of this process, we're closing some older issues that haven't seen activity in a while.

If you're receiving this message, it means we're closing this issue. However, we want to assure you that your input is still valuable to us! If you believe this issue is still relevant or if you're still experiencing the problem, please don't hesitate to open a new issue.

When opening a new issue, it would be super helpful if you could:

- Provide any updated information about the problem
- Confirm if it's still occurring with the latest version of our software
- Include any additional details that might help us investigate

Thank you for your understanding and continued support of our project. We appreciate your contributions and look forward to addressing any ongoing concerns.

Happy gaming! 🎮
