### ISSUE TITLE
World Guard + Silk Spawners = Errors? 

### ISSUE THREAD

**Issue by timbru31** [timbru31/SilkSpawners#62]
```java
[13:52:12 ERROR]: Could not pass event BlockBreakEvent to SilkSpawners v3.7.4
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f950f8e-a710176]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f950f8e-a710176]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-a710176]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-a710176]
    at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [spigot.jar:git-Spigot-f950f8e-a710176]
    at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [spigot.jar:git-Spigot-f950f8e-a710176]
    at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:835) [spigot.jar:git-Spigot-f950f8e-a710176]
    at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-f950f8e-a710176]
    at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-f950f8e-a710176]
    at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-a710176]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-a710176]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-a710176]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-a710176]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-a710176]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-a710176]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
    at com.sk89q.worldguard.bukkit.WorldConfiguration.getBoolean(WorldConfiguration.java:219) ~[?:?]
    at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:344) ~[?:?]
    at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:211) ~[?:?]
    at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:228) ~[?:?]
    at com.sk89q.worldguard.bukkit.WorldGuardPlugin.hasPermission(WorldGuardPlugin.java:508) ~[?:?]
    at com.sk89q.worldguard.protection.GlobalRegionManager.hasBypass(GlobalRegionManager.java:122) ~[?:?]
    at com.sk89q.worldguard.protection.GlobalRegionManager.canBuild(GlobalRegionManager.java:163) ~[?:?]
    at com.sk89q.worldguard.bukkit.WorldGuardPlugin.canBuild(WorldGuardPlugin.java:993) ~[?:?]
    at de.dustplanet.util.SilkUtil.canBuildHere(SilkUtil.java:963) ~[?:?]
    at de.dustplanet.silkspawners.listeners.SilkSpawnersBlockListener.onBlockBreak(SilkSpawnersBlockListener.java:56) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor402.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-f950f8e-a710176]
    ... 17 more
```
 
Silk Spawners, is unfortunately the source for dismay on my server at the moment, as World Guard is interfering with the placement or the silking of spawners. Above is the error generated by the server when attempting to silk touch a spawner.

---
_Migrated from https://dev.bukkit.org/projects/silkspawners/issues/126_

**Comment by timbru31** [comment]
Might be related:
https://pastebin.com/bNbiWH02

**Comment by timbru31** [comment]
https://github.com/timbru31/SilkSpawners/issues/90#issuecomment-317538774
